Deployment:
replicaCount: 1
name: my-nginx-dev
image:
  repository: ghcr.io/dshmelev/jetbrain-task
  pullPolicy: IfNotPresent
resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 128Mi
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


service:
  type: ClusterIP
  port: 80
  name: my-service-dev

ingress:
  enabled: false
  hosts: []

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

env:
  secret: {}